# toml-docs-start lang-main
[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "Elsa Sánchez"
    [en.params.feature]
        link = "/en/about"
        caption = "About me"
    [en.params.footer]
        license = ""
        socialTitle = "Follow me"
        socialCaption = ""
# toml-docs-end lang-param

[es]
    languageName = "Español"
    contentDir = "content/es"
    weight = 2
    [es.params.head]
        tagline = "Elsa Sánchez"
    [es.params.feature]
        link = "/es/about"
        caption = "Sobre mí"
    [es.params.footer]
        license = ""
        socialTitle = "Follow me"
        socialCaption = ""