# toml-docs-start main
[main]
    separator = "-"
    description = ""
    enableDarkMode = false
# toml-docs-end main

# toml-docs-start docs
[docs]
    version = "0.8"
    basePath = ""
# toml-docs-end docs

# toml-docs-start home
[home]
    sections = ["books"]
    featured = true
    featurePhoto = "/img/mila.jpg"
    fullCover = false
    style = ""
# toml-docs-end home

# toml-docs-start navigation
[navigation]
    logo = "img/logo-round.png"
    color = "body"
    fixed = true
    offset = "4em"
    search = false
    breadcrumb = false
    toc = true
    sidebar = true
# toml-docs-end navigation

# toml-docs-start list
[list]
    [books]
        title = ""
        sort = "date"
        reverse = true
        cols = 1
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 align-items-center justify-content-center"
        homepage = 10
    [projects]
        title = "Illustrations"
        sort = "title"
        reverse = false
        cols = 1
        color = ""
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal"
        style = "border-1 card-emphasize"
        homepage = 0
# toml-docs-end list

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#D43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
# toml-docs-end theme-colors
    themeOpacity = "10"
# toml-docs-start font
    themeFont = "Petrona"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Petrona:wght@200;300;600&display=swap"
# toml-docs-end font

[schema]
    type = "Organization"
    name = "Elsa Sánchez"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    # github = "https://github.com/gethinode/hinode"
    section = "books"
    [author]
        name = "Elsa Sánchez"
        # twitter = "https://twitter.com/markdumay"
        # linkedin = "https://www.linkedin.com/in/markdumay/"
        # instagram = "https://github.com/markdumay"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"
