[[main]]
  name = "About"
  url = "about/"
  weight = 10

[[main]]
  name = "Books"
  url = "books/"
  weight = 20

#[[main]]
#  name = "Illustrations"
#  url = "projects/"
#  weight = 30

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://linkedin.com/"
  weight = 10

# toml-docs-start sample-navigation
[[sample]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  url = "/en/projects/sample-project/"
  parent = "Projects"
  weight = 1
# toml-docs-end sample-navigation